pipeline{
    agent any
    stages{
        stage("docker clean up"){
            steps{
                docker rm -f $(docker ps -qa)
            }
        }
        stage("docker build"){
            steps{
                docker build -t flask-app:latest flask-app
            }
        }
        stage("docker run"){
            steps{
                docker run -d \
                  -e MYSQL_ROOT_PASSWORD=password \
                  --name flask-app \
                  -p 5500:80 \
                  flask-app:latest
            }
        }
    }
}
